server:
  port: 8081
  servlet:
    context-path: /demo
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
  application:
    name: demo
  profiles:
    active: dev

logging:
  config: classpath:logback-spring.xml 